<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CharactersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('characters')->insert([
            [
                'name' => 'Jett',
                'image' => 'jett.png',
                'role' => 'Duelista',
                'biography' => 'Proviene de corea del sur. el ágil y evasivo estilo de pelea de jett le permite enfrentarse a riesgos que otros no pueden. Es imparable en todos los enfrentamientos y acaba con sus enemigos antes de que sepan qué los atacó.',
                'q_title' => 'Ráfaga ascendente',
                'q_text' => 'Propulsa a jett hacia el aire al instante.',
                'e_title' => 'Impulso ciclón',
                'e_text' => 'Propulsa al instante a jett hacia la dirección a la que se dirige. Si no se está moviendo, se propulsará hacia adelante',
                'c_title' => 'Nube explosiva',
                'c_text' => 'Lanza un proyectil al instante que se convierte en una nube que bloquea la visión al impactar alguna superficie. Mantén presionada la tecla de la habilidad para cambiar la trayectoria del humo hacia donde apuntes',
                'x_title' => 'Tormenta de cuchillas',
                'x_text' => 'Equipa un conjunto de cuchillos de gran precisión que se recargan al asesinar a un oponente. Dispara para lanzar un cuchillo hacia tu objetivo y usa el disparo secundario para lanzar todos los cuchillos restantes',
                'created_at' => date('Y-m-d H-i-s'),
                'updated_at' => date('Y-m-d H-i-s'),
            ],
            [
                'name' => 'Raze',
                'image' => 'raze.png',
                'role' => 'Duelista',
                'biography' => 'Raze llega de brasil con su explosiva personalidad y sus grandes armas. Gracias a su contundente estilo de juego, es muy buena para separar los enemigos atrincherados y para despejar espacios estrechos con una gran cantidad de explosiones.',
                'q_title' => 'Paquete explosivo',
                'q_text' => 'Lanza al instante un paquete explosivo que se adhiere a las superficies. Vuelve a usar la habilidad después de desplegar el paquete para detonarlo, lo que dañará y desplazará todo a su alcance. Raze no recibe daño por esta habilidad, pero sí sufrirá daño por caídas si salta muy alto ',
                'e_title' => 'Carcasas de pintura',
                'e_text' => 'Equipa una granada de racimo y dispara para lanzarla. La granada infligirá daño por su cuenta y creará submuniciones que también infligirán daño a cualquiera que se encuentre dentro de su alcance',
                'c_title' => 'Bumbot',
                'c_text' => 'Equipa un bumbot y dispara para desplegarlo. El bot se moverá en línea recta por el suelo y rebotará en los muros. El bumbot marcará a cualquier enemigo que se encuentre en un cono frente a él y lo perseguirá. Si lo alcanza, explotará e infligirá daño masivo',
                'x_title' => 'Tumbadivas',
                'x_text' => 'Equipa un lanzamisiles. Dispara para lanzar un misil que inflige daño de área masivo al entrar en contacto con algo',
                'created_at' => date('Y-m-d H-i-s'),
                'updated_at' => date('Y-m-d H-i-s'),
            ],
            [
                'name' => 'Breach',
                'image' => 'breach.png',
                'role' => 'Iniciador',
                'biography' => 'Breach, el sueco biónico, lanza poderosas ráfagas cinéticas para abrirse paso a la fuerza a través del territorio enemigo. El daño y la interrupción que inflige garantizarán que ninguna pelea sea justa.',
                'q_title' => 'Fulgor',
                'q_text' => 'Equipa una carga cegadora y dispara para lanzar una ráfaga de acción rápida a través de una pared. La carga detonará y cegará a todos los jugadores que la vean',
                'e_title' => 'Falla sísmica',
                'e_text' => 'Equipa un rayo sísmico y mantén presionado el botón de disparo para aumentar la distancia. Suéltalo para iniciar el temblor y aturdir a todos los jugadores que estén en la zona',
                'c_title' => 'Réplica',
                'c_text' => 'Equipa una carga de fusión y dispara para lanzar una ráfaga de acción lenta a través de una pared. La ráfaga infligirá daño masivo a todos los que estén en su alcance',
                'x_title' => 'Trueno rodante',
                'x_text' => 'Equipa una carga sísmica y dispara para enviar un temblor en cascada por una gran zona cónica. El temblor aturde y lanza por el aire a todos los que impacta',
                'created_at' => date('Y-m-d H-i-s'),
                'updated_at' => date('Y-m-d H-i-s'),
            ],
            [
                'name' => 'Omen',
                'image' => 'omen.png',
                'role' => 'Controlador',
                'biography' => 'Un espectro de la memoria, Omen caza entre las sombras, ciega a los enemigos, se transporta a través del campo de batalla y deja que la paranoia los invada mientras intentan descubrir dónde atacará.',
                'q_title' => 'Paranoia',
                'q_text' => 'Lanza proyectil de sombras que reduce el alcance de visión de todos los jugadores a los que alcanza durante un breve periodo. Este proyectil puede atravesar paredes',
                'e_title' => 'Manto oscuro',
                'e_text' => 'Equipa un orbe de sombras y mira su indicador de alcance. Dispara para lanzarlo hacia la ubicación marcada. el orbe creará una esfera de sombras de larga duración que bloquea la visión. Mantén presionado el botón de disparo secundario mientras apuntas para alejar el marcador. Mantén presionada la tecla de la habilidad mientras apuntas para acercar el marcador',
                'c_title' => 'Paso sombrío',
                'c_text' => 'Equipa la habilidad paso sombrío y mira su indicador de alcance. Dispara para comenzar una breve canalización y luego teletranspórtate hacia la ubicación marcada',
                'x_title' => 'Desde las sombras',
                'x_text' => 'Equipa un mapa estratégico. Dispara para empezar a teletransportarte hacia la ubicación seleccionada. mientras te teletransportas, omen lucirá como una sombra que los enemigos podrán destruir para cancelar su teletransportación',
                'created_at' => date('Y-m-d H-i-s'),
                'updated_at' => date('Y-m-d H-i-s'),
            ],
            [
                'name' => 'Brimstone',
                'image' => 'brimstone.png',
                'role' => 'Controlador',
                'biography' => 'Proveniente de estados unidos, brimstone proporciona una constante ventaja para su equipo con su arsenal orbital. Su habilidad otorga información de forma precisa y a distancia, lo que lo hace un comandante sin igual en el campo.',
                'q_title' => 'La incendiaria',
                'q_text' => 'Equipa un lanzagranadas incendiario y dispara para lanzar una granada que explota cuando se detiene en el suelo. Esta crea una zona de fuego que permanece en el campo y daña a los enemigos que estén dentro de ella',
                'e_title' => 'Humo celestial',
                'e_text' => 'Equipa un mapa estratégico y dispara para marcar las ubicaciones en las que caerán las nubes de humo de brimstone. Usa el disparo secundario para confirmar y lanzar nubes de humo de larga duración que bloquearán la visión en la zona seleccionada',
                'c_title' => 'Baliza potenciadora',
                'c_text' => 'Equipa una baliza potenciadora y dispara para lanzarla frente a brimstone. al caer, resguardo potenciador creará un campo que aumenta la velocidad de disparo de los jugadores',
                'x_title' => 'Ataque orbital',
                'x_text' => 'Equipa un mapa estratégico y dispara para lanzar un ataque orbital prolongado de un láser en la ubicación seleccionada. Este infligirá daño masivo con el tiempo a los jugadores que estén en la zona',
                'created_at' => date('Y-m-d H-i-s'),
                'updated_at' => date('Y-m-d H-i-s'),
            ],
            [
                'name' => 'Phoenix',
                'image' => 'phoenix.png',
                'role' => 'Duelista',
                'biography' => 'Proviene del reino unido. El poder estelar de phoenix se manifiesta en su estilo de combate al incendiar el campo de batalla con sus granadas aturdidoras y cegadoras. Sin importar si cuenta con apoyo o no, participará en la batalla bajo sus propios términos.',
                'q_title' => 'Destello en curva',
                'q_text' => 'Equipa un orbe cegador que recorre una trayectoria curva y detona poco después de lanzarlo. Dispara para cambiar la trayectoria del orbe cegador hacia la izquierda. Este detonará y cegará a cualquier jugador que lo vea. Usa el disparo secundario para cambiar su trayectoria hacia la derecha',
                'e_title' => 'Manitas calientes',
                'e_text' => 'Equipa una bola de fuego y dispara para lanzarla. Esta explotará tras cierto tiempo o al impactar el suelo, lo que creará una zona de fuego que permanecerá en el campo y dañará a los enemigos',
                'c_title' => 'Muro abrasador',
                'c_text' => 'Equipa un muro de fuego y dispara para crear una hilera de llamas que avanza, lo que creará un muro que bloquea la visión y dañará a los jugadores que lo atraviesen. Mantén presionado el botón de disparo para mover el muro en la dirección de tu retícula',
                'x_title' => 'Va de fuego',
                'x_text' => 'Coloca al instante un marcador en la ubicación de phoenix. Cuando esta habilidad esté activa, morir o dejar que el temporizador expire hará que la habilidad se termine y regresará a phoenix a esa ubicación con toda su vida',
                'created_at' => date('Y-m-d H-i-s'),
                'updated_at' => date('Y-m-d H-i-s'),
            ],
            [
                'name' => 'Sage',
                'image' => 'sage.png',
                'role' => 'Centinela',
                'biography' => 'El bastión de china. Sage proporciona seguridad para sí misma y para su equipo en cualquier lugar. Gracias a su capacidad de revivir a sus compañeros caídos y evitar ataques agresivos, les da un lugar de protección en medio de la caótica pelea.',
                'q_title' => 'Orbe ralentizador',
                'q_text' => 'Equipa un orbe de ralentización y dispara para lanzarlo. Este detonará al caer al suelo y creará un campo que permanecerá en la zona y ralentizará a los jugadores que estén dentro de él',
                'e_title' => 'Orbe curativo',
                'e_text' => 'Equipa un orbe curativo y dispara tras apuntar a un aliado herido para curarlo con el tiempo. Usa el disparo secundario cuando sage esté herida para curarla con el tiempo',
                'c_title' => 'Orbe de barrera',
                'c_text' => 'Equipa un orbe de barrera. Dispara para colocar una pared sólida. Usa el disparo secundario para rotarla antes de crearla',
                'x_title' => 'Resurrección',
                'x_text' => 'Equipa una habilidad de resurrección y dispara mientras apuntas hacia un aliado muerto para comenzar a resucitarlo. Tras un breve periodo de canalización, el aliado revivirá con toda su vida',
                'created_at' => date('Y-m-d H-i-s'),
                'updated_at' => date('Y-m-d H-i-s'),
            ],
            [
                'name' => 'Sova',
                'image' => 'sova.png',
                'role' => 'Iniciador',
                'biography' => 'Proveniente de la tundra del eterno invierno de rusia. Sova rastrea, encuentra y elimina a sus enemigos con gran eficiencia y precisión. Su arco personalizado y sus increíbles habilidades de exploración impedirán que sus enemigos puedan esconderse de él.',
                'q_title' => 'Proyectil eléctrico',
                'q_text' => 'Equipa un arco con un proyectil eléctrico y dispara para lanzarlo. El proyectil detonará al impactar y dañará a los jugadores cercanos. Mantén presionado el botón de disparo para aumentar el alcance del proyectil. Usa el disparo secundario para añadir hasta dos rebotes a su trayectoria',
                'e_title' => 'Proyectil rastreador',
                'e_text' => 'Equipa un arco con un proyectil rastreador y dispara para lanzarlo. El proyectil se activará al impactar y revelará la ubicación de los enemigos cercanos que estén dentro de su alcance. Mantén presionado el botón de disparo para aumentar el alcance del proyectil. Usa el disparo secundario para añadir hasta dos rebotes a la trayectoria de la flecha',
                'c_title' => 'Dron búho',
                'c_text' => 'Equipa un dron búho y dispara para desplegarlo y controlar su movimiento. Mientras lo controlas, dispara para lanzar un dardo marcador que revelará la ubicación de cualquier jugador al que impacte',
                'x_title' => 'Furia del cazador',
                'x_text' => 'Equipa un arco con tres ráfagas de energía de largo alcance que atraviesan las paredes. Dispara para lanzar una ráfaga de energía frente a sova que infligirá daño y revelará la ubicación de los enemigos impactados. Puedes volver a usar esta habilidad hasta dos veces más mientras su contador esté activo',
                'created_at' => date('Y-m-d H-i-s'),
                'updated_at' => date('Y-m-d H-i-s'),
            ],
            [
                'name' => 'Viper',
                'image' => 'viper.png',
                'role' => 'Controlador',
                'biography' => 'Química estadounidense, viper despliega varios artefactos químicos venenosos para controlar el campo de batalla y afectar la visión de los enemigos. Si las toxinas no asesinan a su presa, sin duda lo harán sus juegos mentales.',
                'q_title' => 'Nube venenosa',
                'q_text' => 'Equipa un emisor de gas y dispara para lanzarlo. Este permanecerá ahí durante toda la ronda. Vuelve a usar la habilidad para crear una nube de gas tóxica que usa combustible. Puedes volver a usar esta habilidad varias veces y puedes recuperarla para volver a desplegarla',
                'e_title' => 'Cortina tóxica',
                'e_text' => 'Equipa un lanzador de gas y dispara para desplegar una larga hilera de emisores de gas. Vuelve a usar la habilidad para crear un muro de gas tóxico que usa combustible. Puedes volver a usar esta habilidad varias veces',
                'c_title' => 'Mordedura',
                'c_text' => 'Equipa un lanzador de químicos. Dispara para lanzar un contenedor que se rompe al impactar contra el suelo. Este crea una zona química que permanece en el campo, la cual daña y ralentiza a los enemigos',
                'x_title' => 'Fosa vipérea',
                'x_text' => 'Equipa un rociador y dispara para lanzar una nube de químicos en todas las direcciones alrededor de viper, lo que crea una gran nube que reduce el alcance de visión y la vida máxima de los jugadores que estén dentro de ella',
                'created_at' => date('Y-m-d H-i-s'),
                'updated_at' => date('Y-m-d H-i-s'),
            ],
            [
                'name' => 'Cypher',
                'image' => 'cypher.png',
                'role' => 'Centinela',
                'biography' => 'Cypher, el agente de información marroquí, es un sistema de vigilancia de un solo hombre que puede monitorear todos los movimientos de sus enemigos. No hay secreto que no descubra ni maniobra que no detecte. Cypher siempre está vigilando.',
                'q_title' => 'Ciberjaula',
                'q_text' => 'Lanza al instante una ciberjaula frente a cypher. Actívala para crear una zona que bloquea la visión y ralentiza a los enemigos que la atraviesan',
                'e_title' => 'Cámara espía',
                'e_text' => 'Equipa una cámara espía. Dispara para colocarla en la ubicación seleccionada. Vuelve a usar esta habilidad para tomar el control de la vista de la cámara. Mientras la controlas, dispara para lanzar un dardo marcador que revelará la ubicación de cualquier jugador al que impacte',
                'c_title' => 'Cable trampa',
                'c_text' => 'Equipa un cable trampa. Dispara para colocar un cable trampa destructible y camuflado en la ubicación seleccionada que creará una línea entre ese lugar y la pared opuesta. Los jugadores enemigos que activen el cable trampa quedarán atados, revelados y aturdidos tras un momento si no destruyen el dispositivo a tiempo. Puedes recogerlo y volver a colocarlo',
                'x_title' => 'Asalto neural',
                'x_text' => 'Apunta hacia un jugador enemigo muerto y úsalo de inmediato para revelar la ubicación de todos los jugadores enemigos con vida',
                'created_at' => date('Y-m-d H-i-s'),
                'updated_at' => date('Y-m-d H-i-s'),
            ]
            
        ]);
    }
}
